import {createState} from "./game_state.js";import {ScenarioEngine} from "./scenario.js";import * as UI from "./ui.js";import * as Save from "./save.js";
let balance,characters,enemies,state,engine,DEBUG_MODE=false;const $=s=>document.querySelector(s),currency=n=>`${Number(n).toLocaleString("ja-JP")} G`;
async function data(name){try{const r=await fetch(`data/${name}.json?v=${window.CACHE_BUST}`);if(!r.ok)throw Error(r.status);return await r.json()}catch(e){const d=window.DATA_BUNDLE?.[name];if(d)return structuredClone(d);throw Error(`${name}.json を読み込めません: ${e.message}`)}}
async function boot(){try{[balance,characters,enemies]=await Promise.all([data("game_balance"),data("characters"),data("enemies")]);DEBUG_MODE=false;$("#continue-btn").disabled=!Save.hasSave();wire()}catch(e){UI.error(`起動エラー: ${e.message}`)}}
function wire(){$("#start-btn").onclick=()=>start(false);$("#debug-start-btn").onclick=()=>start(true);$("#continue-btn").onclick=continueGame;$("#title-btn").onclick=()=>{UI.showScreen("title");$("#continue-btn").disabled=!Save.hasSave()};$("#save-btn").onclick=()=>{Save.save(engine.snapshot());UI.toast("SAVE COMPLETE")};UI.els.play.addEventListener("click",e=>{if(e.target.closest("button")||UI.els.modal.classList.contains("open"))return;engine?.advance()});addEventListener("keydown",e=>{if((e.key==="Enter"||e.code==="Space")&&!UI.els.modal.classList.contains("open")){e.preventDefault();engine?.advance()}});document.querySelectorAll("[data-debug]").forEach(b=>b.onclick=()=>{const k=b.dataset.debug,{moneyIncrement,bahamutValueIncrement,bahamutConditionIncrement,bahamutTrustIncrement}=balance.debug;if(k==="money")state.money+=moneyIncrement;if(k==="value")state.bahamutValue+=bahamutValueIncrement;if(k==="condition")state.bahamutCondition=Math.min(100,state.bahamutCondition+bahamutConditionIncrement);if(k==="trust")state.bahamutTrust+=bahamutTrustIncrement;render()})}
function makeEngine(){engine=new ScenarioEngine({state,balance,characters,enemies,onState:render,onEnding:()=>Save.clear(),onAutosave:()=>Save.save(engine.snapshot())})}
async function start(debug){state=createState(balance);DEBUG_MODE=debug;makeEngine();UI.showScreen("play");UI.els.debug.classList.toggle("active",DEBUG_MODE);await engine.load("chapter01_intro.json")}
async function continueGame(){const s=Save.load();if(!s)return;DEBUG_MODE=false;state={...createState(balance),...s.gameState,flags:{...(s.gameState.flags||{})}};makeEngine();if(s.visualState)engine.visualState=s.visualState;UI.showScreen("play");UI.els.debug.classList.remove("active");await engine.load(s.scenarioFile,s.sceneId,s.stepIndex)}
function render(){UI.updateStatus(state,currency,DEBUG_MODE);if(DEBUG_MODE&&engine)UI.els.debugValues.textContent+=`\ncurrent: ${engine.file} / ${engine.scene} / ${engine.index}`}
boot();
