const $=s=>document.querySelector(s);export const els={title:$("#title-screen"),play:$("#play-screen"),ending:$("#ending-screen"),bg:$("#background"),text:$("#text"),speaker:$("#speaker"),next:$("#next-mark"),choices:$("#choices"),toast:$("#toast"),chapter:$("#chapter-card"),effect:$("#effect-layer"),status:$("#status"),debug:$("#debug-panel"),debugValues:$("#debug-values"),modal:$("#modal"),modalImage:$("#modal-image"),modalCaption:$("#modal-caption"),error:$("#error-box")};
export function showScreen(name){[els.title,els.play,els.ending].forEach(x=>x.classList.remove("active"));({title:els.title,play:els.play,ending:els.ending}[name]).classList.add("active")}
export function updateStatus(s,loc,debug){$("#money").textContent=loc(s.money);$("#payment").textContent=loc(s.loanPayment);$("#payments").textContent=`${s.loanPaymentsMade} / ${s.loanPaymentsRequired}`;const condition=s.bahamutCondition>=90?"良好":s.bahamutCondition>=60?"普通":"消耗";const trust=s.bahamutTrust>=15?"厚い":s.bahamutTrust>=5?"普通":"まだ薄い";const rank=s.bahamutValue>=80?"A":s.bahamutValue>=65?"B":"C";$("#bahamut-status").innerHTML=`状態：${condition}<br>信頼：${trust}<br>査定予想：${rank}`;if(debug)els.debugValues.textContent=JSON.stringify(s,null,2)}
export function background(name){const path=`../assets/backgrounds/${name}.png`;els.bg.dataset.background=name;els.bg.style.backgroundImage=`url("${path}")`}
export async function prepareBackground(name){if(!name)return;const path=`../assets/backgrounds/${name}.png`;await new Promise(resolve=>{const preload=new Image();preload.onload=resolve;preload.onerror=resolve;preload.src=path});background(name)}
export async function sceneTransition(name){if(els.bg.dataset.background===name)return;const path=`../assets/backgrounds/${name}.png`;await new Promise(resolve=>{const preload=new Image();preload.onload=resolve;preload.onerror=resolve;preload.src=path});const oldBackground=getComputedStyle(els.bg).backgroundImage;els.play.classList.add("transitioning");els.effect.style.backgroundImage=oldBackground;els.effect.className="background-crossfade covered";void els.effect.offsetWidth;background(name);await new Promise(requestAnimationFrame);els.effect.classList.remove("covered");await new Promise(r=>setTimeout(r,570));els.effect.className="";els.effect.style.backgroundImage="";els.play.classList.remove("transitioning")}
export function showCharacter(c,characters){document.querySelectorAll(`[data-character="${c.character}"]`).forEach(el=>el.remove());const slot=$( `.character-slot.${c.position||"center"}`);slot.innerHTML="";const img=new Image();const expression=c.expression||characters[c.character]?.defaultExpression||"normal";const wanted=`../assets/characters/${c.character}/${c.character}_${expression}.png`,fallback=`../assets/characters/${c.character}/${c.character}_normal.png`;img.alt=characters[c.character]?.name||c.character;img.dataset.character=c.character;img.src=wanted;img.style.transform=`scale(${characters[c.character]?.scale||1})`;img.onerror=()=>{if(!img.dataset.fallback){console.warn("Missing asset:",wanted);img.dataset.fallback="1";img.src=fallback}else{console.warn("Missing asset:",fallback);slot.innerHTML=`<div class="placeholder" data-character="${c.character}">${img.alt}</div>`}};slot.append(img)}
export function hideCharacter(id){document.querySelectorAll(`[data-character="${id}"]`).forEach(el=>el.remove())}export function hideAll(){document.querySelectorAll(".character-slot").forEach(s=>s.innerHTML="")}
export function choices(options,handler){els.choices.innerHTML="";options.forEach((o,i)=>{const b=document.createElement("button");b.textContent=o.text;b.onclick=()=>{els.choices.innerHTML="";handler(o,i)};els.choices.append(b)})}
export function toast(text,ms=1150){return new Promise(r=>{els.toast.textContent=text;els.toast.classList.add("show");setTimeout(()=>{els.toast.classList.remove("show");r()},ms)})}
export function chapter(title){els.play.classList.add("chapter-active");els.chapter.textContent=title;els.chapter.classList.add("show");return new Promise(resolve=>setTimeout(()=>{els.chapter.classList.remove("show");els.play.classList.remove("chapter-active");resolve()},1500))}
export function effect(name){els.effect.className=name;setTimeout(()=>els.effect.className="",1000)}
export function documentModal(name){return new Promise(resolve=>{els.modalImage.src=`../assets/documents/${name}.png`;els.modalCaption.textContent=name==="bahamut_contract"?"バハムート残価クレジット契約書":"ローン請求書";els.modal.classList.add("open");const close=()=>{els.modal.classList.remove("open");els.modal.onclick=null;$("#modal-close").onclick=null;resolve()};els.modal.onclick=e=>{if(e.target===els.modal)close()};$("#modal-close").onclick=close})}
export function ending(step){$("#ending-title").textContent=step.title;$("#ending-text").textContent=step.text;showScreen("ending")}
export function error(message){els.error.textContent=message;els.error.style.display="block"}
