const $=s=>document.querySelector(s);export const els={title:$("#title-screen"),play:$("#play-screen"),ending:$("#ending-screen"),bg:$("#background"),text:$("#text"),speaker:$("#speaker"),next:$("#next-mark"),choices:$("#choices"),toast:$("#toast"),chapter:$("#chapter-card"),effect:$("#effect-layer"),status:$("#status"),debug:$("#debug-panel"),debugValues:$("#debug-values"),modal:$("#modal"),modalImage:$("#modal-image"),modalCaption:$("#modal-caption"),error:$("#error-box"),battle:$("#battle-panel")};
const preloadedImages=new Map();export function preloadVisualAssets(characters,enemies,scenarios){const urls=new Set();for(const scenario of Object.values(scenarios||{}))for(const scene of Object.values(scenario.scenes||{}))for(const step of scene.steps||[]){if(step.type==="background")urls.add(`../assets/backgrounds/${step.name}.png`);if(step.type==="showCharacter"){const expression=step.expression||characters[step.character]?.defaultExpression||"normal";urls.add(`../assets/characters/${step.character}/${step.character}_${expression}.png`)}if(step.type==="showEnemy"){const enemy=enemies[step.enemy]||{};urls.add(`../${enemy.asset||`assets/enemies/${step.enemy}.png`}`)}if(step.type==="document")urls.add(`../assets/documents/${step.name}.png`)}for(const url of urls){const versioned=`${url}?v=${window.CACHE_BUST}`;if(preloadedImages.has(versioned))continue;const img=new Image();preloadedImages.set(versioned,img);img.onerror=()=>console.warn("Background preload failed:",url);img.src=versioned}console.debug("Visual assets preloading",urls.size)}
export function showScreen(name){[els.title,els.play,els.ending].forEach(x=>x.classList.remove("active"));({title:els.title,play:els.play,ending:els.ending}[name]).classList.add("active")}
export function updateStatus(s,loc,debug){els.status.classList.toggle("contract-locked",!s.flags?.signedContract);$("#money").textContent=loc(s.money);$("#payment").textContent=loc(s.loanPayment);$("#payments").textContent=`${s.loanPaymentsMade} / ${s.loanPaymentsRequired}`;const condition=s.bahamutCondition>=90?"良好":s.bahamutCondition>=60?"普通":"消耗";const trust=s.bahamutTrust>=15?"厚い":s.bahamutTrust>=5?"普通":"まだ薄い";const rank=s.bahamutValue>=80?"A":s.bahamutValue>=65?"B":"C";$("#bahamut-status").innerHTML=`状態：${condition}<br>信頼：${trust}<br>査定予想：${rank}`;if(debug)els.debugValues.textContent=JSON.stringify(s,null,2)}
export function background(name){const path=`../assets/backgrounds/${name}.png?v=${window.CACHE_BUST}`;els.bg.dataset.background=name;els.bg.style.backgroundImage=`url("${path}")`}
export async function prepareBackground(name){if(!name)return;const path=`../assets/backgrounds/${name}.png?v=${window.CACHE_BUST}`;await new Promise(resolve=>{const preload=new Image();preload.onload=resolve;preload.onerror=resolve;preload.src=path});background(name)}
export async function sceneTransition(name){if(els.bg.dataset.background===name)return;const path=`../assets/backgrounds/${name}.png?v=${window.CACHE_BUST}`;await new Promise(resolve=>{const preload=new Image();preload.onload=resolve;preload.onerror=resolve;preload.src=path});const oldBackground=getComputedStyle(els.bg).backgroundImage;els.play.classList.add("transitioning");els.effect.style.backgroundImage=oldBackground;els.effect.className="background-crossfade covered";void els.effect.offsetWidth;background(name);await new Promise(requestAnimationFrame);els.effect.classList.remove("covered");await new Promise(r=>setTimeout(r,570));els.effect.className="";els.effect.style.backgroundImage="";els.play.classList.remove("transitioning")}
export function showCharacter(c,characters){document.querySelectorAll(`[data-character="${c.character}"]`).forEach(el=>el.remove());const slot=$( `.character-slot.${c.position||"center"}`);slot.innerHTML="";const img=new Image();const expression=c.expression||characters[c.character]?.defaultExpression||"normal";const wanted=`../assets/characters/${c.character}/${c.character}_${expression}.png?v=${window.CACHE_BUST}`,fallback=`../assets/characters/${c.character}/${c.character}_normal.png?v=${window.CACHE_BUST}`;img.alt=characters[c.character]?.name||c.character;img.dataset.character=c.character;img.src=wanted;img.style.transform=`scale(${characters[c.character]?.scale||1})`;img.onerror=()=>{if(!img.dataset.fallback){console.warn("Missing asset:",wanted);img.dataset.fallback="1";img.src=fallback}else{console.warn("Missing asset:",fallback);slot.innerHTML=`<div class="placeholder" data-character="${c.character}">${img.alt}</div>`}};slot.append(img)}
export function hideCharacter(id){document.querySelectorAll(`[data-character="${id}"]`).forEach(el=>el.remove())}export function hideAll(){document.querySelectorAll(".character-slot").forEach(s=>s.innerHTML="")}
export function showEnemy(id,enemies){const layer=$("#enemy-layer"),data=enemies[id]||{};els.play.classList.add("enemy-active");layer.innerHTML="";const img=new Image();img.alt=data.name||id;img.dataset.enemy=id;img.src=`../${data.asset||`assets/enemies/${id}.png`}?v=${window.CACHE_BUST}`;img.onerror=()=>{console.warn("Missing asset:",img.src);layer.innerHTML=`<div class="placeholder" data-enemy="${id}">${img.alt}</div>`};layer.append(img)}export function hideEnemy(){els.play.classList.remove("enemy-active");$("#enemy-layer").innerHTML=""}
export function choices(options,handler){els.choices.innerHTML="";options.forEach((o,i)=>{const b=document.createElement("button");b.textContent=o.text;b.onclick=()=>{els.choices.innerHTML="";handler(o,i)};els.choices.append(b)})}
export function renderRpgBattle(b,onAction){els.play.classList.add("battle-active");els.play.classList.toggle("god-battle",b.enemy==="god");$("#battle-hero-hp").textContent=`HP ${b.heroHp} / ${b.heroMaxHp}`;$("#battle-hero-stats").textContent=`LV ${b.heroLevel}　攻撃力 ${b.heroAttack}`;$("#battle-enemy-name").textContent=b.name;$("#battle-enemy-hp").textContent=`HP ${b.enemyHp} / ${b.enemyMaxHp}`;$("#battle-hero-bar").style.width=`${b.heroHp/b.heroMaxHp*100}%`;$("#battle-enemy-bar").style.width=`${b.enemyHp/b.enemyMaxHp*100}%`;$("#battle-turn").textContent=`TURN ${b.turn}`;$("#battle-log").textContent=b.log;document.querySelectorAll("[data-battle-action]").forEach(button=>{const action=button.dataset.battleAction;if(action==="bahamut")button.textContent=b.alliesAuto?"仲間が自動攻撃":"バハムート";button.disabled=b.ended||(action==="potion"&&b.potionUsed)||(action==="bahamut"&&(b.bahamutUsed||b.alliesAuto));button.onclick=()=>onAction(action)})}export function closeRpgBattle(){els.play.classList.remove("battle-active","god-battle");document.querySelectorAll("[data-battle-action]").forEach(button=>{button.onclick=null;if(button.dataset.battleAction==="bahamut")button.textContent="バハムート"})}
export function toast(text,ms=1150){return new Promise(r=>{els.toast.textContent=text;els.toast.classList.add("show");setTimeout(()=>{els.toast.classList.remove("show");r()},ms)})}
export function chapter(title){els.play.classList.add("chapter-active");els.chapter.textContent=title;els.chapter.classList.add("show");return new Promise(resolve=>setTimeout(()=>{els.chapter.classList.remove("show");els.play.classList.remove("chapter-active");resolve()},1500))}
export function effect(name){els.effect.className=name;setTimeout(()=>els.effect.className="",1000)}
export function documentModal(name){return new Promise(resolve=>{els.modalImage.src=`../assets/documents/${name}.png?v=${window.CACHE_BUST}`;els.modalCaption.textContent=name==="bahamut_contract"?"バハムート残価クレジット契約書":"ローン請求書";els.modal.classList.add("open");const close=()=>{els.modal.classList.remove("open");els.modal.onclick=null;$("#modal-close").onclick=null;resolve()};els.modal.onclick=e=>{if(e.target===els.modal)close()};$("#modal-close").onclick=close})}
export function ending(step){$("#ending-title").textContent=step.title;$("#ending-text").textContent=step.text;showScreen("ending")}
export function error(message){els.error.textContent=message;els.error.style.display="block"}
